export interface ITraining {
    id: number;
    name: string;
    organisation: string;
    description: string;
    financer: string;
    dateBeg: Date;
    dateEnd: Date;
    durationHours: number;
    dateUpload: Date;
    prerequisites: string[];
    keywords: string[];


}
export let MOCK_TRAINING : ITraining[] = [
    {
        id: 1,
        name:'Developpeur',
        organisation:'Centre1',
        description:'linktraining1',
        financer: 'OPCO',
        dateBeg: new Date(2020,3,23),
        dateEnd: new Date(2020,6,23),
        durationHours: 20,
        dateUpload: new Date(2019,6,23),
        prerequisites: ['JAVASCRIPT', 'HTML'],
        keywords: ['JAVA', 'PYTHON'],
    },
    {
        id: 2,
        name:'Codeur',
        organisation:'Centre2',
        description:'linktraining2',
        financer: 'OPCO',
        dateBeg: new Date(2020,4,21),
        dateEnd: new Date(2020,6,22),
        durationHours: 20,
        dateUpload: new Date(2019,5,23),
        prerequisites: ['JAVASCRIPT', 'HTML'],
        keywords: ['PYTHON', 'ANGULAR'],
    },
    {
        id: 3,
        name:'Integrateur',
        organisation:'Centre3',
        description:'linktraining3',
        financer: 'DIF',
        dateBeg: new Date(2020,2,23),
        dateEnd: new Date(2020,4,23),
        durationHours: 10,
        dateUpload: new Date(2019,4,23),
        prerequisites: ['HTML'],
        keywords: ['PYTHON', 'ANGULAR'],
    },
    {
        id: 4,
        name:'Scrumaster',
        organisation:'Centre4',
        description:'linktraining4',
        financer: 'OPCA',
        dateBeg: new Date(2020,1,3),
        dateEnd: new Date(2020,4,30),
        durationHours: 30,
        dateUpload: new Date(2019,6,25),
        prerequisites: ['CSS', 'HTML'],
        keywords: ['PYTHON'],
    },
    {
        id: 5,
        name:'Developpeur',
        organisation:'Centre5',
        description:'linktraining5',
        financer: 'OPCO',
        dateBeg: new Date(2020,3,23),
        dateEnd: new Date(2020,6,23),
        durationHours: 70,
        dateUpload: new Date(2019,6,23),
        prerequisites: ['CSS', 'HTML'],
        keywords: ['JAVA', 'ANGULAR'],
    },
    {
        id: 6,
        name:'Developpeur',
        organisation:'Centre6',
        description:'linktraining6',
        financer: 'DIF',
        dateBeg: new Date(2020,4,21),
        dateEnd: new Date(2020,6,22),
        durationHours: 20,
        dateUpload: new Date(2019,5,23),
        prerequisites: ['VISUALCODE'],
        keywords: ['JAVA'],
    },
    {
        id: 7,
        name:'Codeur',
        organisation:'Centre7',
        description:'linktraining7',
        financer: 'DIF',
        dateBeg: new Date(2020,2,21),
        dateEnd: new Date(2020,4,20),
        durationHours: 40,
        dateUpload: new Date(2019,3,15),
        prerequisites: ['CODA'],
        keywords: ['PYTHON', 'ANGULAR'],
    },
    {
        id: 8,
        name:'Integrateur',
        organisation:'Centre8',
        description:'linktraining8',
        financer: 'OPCA',
        dateBeg: new Date(2020,11,3),
        dateEnd: new Date(2020,12,30),
        durationHours: 10,
        dateUpload: new Date(2019,6,25),
        prerequisites: ['PYCHARM'],
        keywords: ['PYTHON'],
    },
    {
        id: 9,
        name:'Codeur',
        organisation:'Centre9',
        description:'linktraining9',
        financer: 'OPCO',
        dateBeg: new Date(2020,3,20),
        dateEnd: new Date(2020,6,19),
        durationHours: 20,
        dateUpload: new Date(2019,4,13),
        prerequisites: ['PYCHARM'],
        keywords: ['JAVA', 'PYTHON', 'ANGULAR'],
    },
    {
        id: 10,
        name:'Developpeur',
        organisation:'Centre3',
        description:'linktraining10',
        financer: 'DIF',
        dateBeg: new Date(2020,4,17),
        dateEnd: new Date(2020,6,10),
        durationHours: 40,
        dateUpload: new Date(2019,4,28),
        prerequisites: ['CSS', 'HTML', 'CODA'],
        keywords: ['ANGULAR'],
    },
    {
        id: 11,
        name:'Developpeur',
        organisation:'Centre1',
        description:'linktraining11',
        financer: 'OPCO',
        dateBeg: new Date(2020,1,23),
        dateEnd: new Date(2020,4,30),
        durationHours: 80,
        dateUpload: new Date(2019,8,23),
        prerequisites: ['CSS', 'HTML', 'SUBLIMETEXT'],
        keywords: ['PYTHON', 'ANGULAR'],
    },
    {
        id: 12,
        name:'Scrumaster',
        organisation:'Centre2',
        description:'linktraining12',
        financer: 'OPCA',
        dateBeg: new Date(2020,1,3),
        dateEnd: new Date(2020,4,30),
        durationHours: 30,
        dateUpload: new Date(2019,6,25),
        prerequisites: ['CSS', 'HTML', 'PYCHARM'],
        keywords: ['PYTHON'],
    },
    {
        id: 13,
        name:'Codeur',
        organisation:'Centre3',
        description:'linktraining13',
        financer: 'OPCO',
        dateBeg: new Date(2020,3,23),
        dateEnd: new Date(2020,6,23),
        durationHours: 40,
        dateUpload: new Date(2019,6,23),
        prerequisites: ['CSS', 'HTML', 'SUBLIMTEXT'],
        keywords: ['JAVA', 'PYTHON', 'ANGULAR'],
    },
    {
        id: 14,
        name:'Developpeur',
        organisation:'Centre4',
        description:'linktraining14',
        financer: 'DIF',
        dateBeg: new Date(2020,2,21),
        dateEnd: new Date(2020,6,22),
        durationHours: 140,
        dateUpload: new Date(2019,5,23),
        prerequisites: ['CSS', 'HTML', 'PYCHARM'],
        keywords: ['JAVA'],
    },
    {
        id: 15,
        name:'Codeur',
        organisation:'Centre8',
        description:'linktraining15',
        financer: 'DIF',
        dateBeg: new Date(2020,7,21),
        dateEnd: new Date(2020,12,20),
        durationHours: 100,
        dateUpload: new Date(2020,3,15),
        prerequisites: ['JAVASCRIPT', 'HTML'],
        keywords: ['PYTHON', 'ANGULAR'],
    },
    {
        id: 16,
        name:'Integrateur',
        organisation:'Centre6',
        description:'linktraining16',
        financer: 'OPCA',
        dateBeg: new Date(2020,11,3),
        dateEnd: new Date(2020,12,30),
        durationHours: 20,
        dateUpload: new Date(2019,6,25),
        prerequisites: ['HTML'],
        keywords: ['PYTHON'],
    },
    {
        id: 17,
        name:'Developpeur',
        organisation:'Centre7',
        description:'linktraining17',
        financer: 'OPCA',
        dateBeg: new Date(2020,2,23),
        dateEnd: new Date(2020,4,23),
        durationHours: 60,
        dateUpload: new Date(2019,4,23),
        prerequisites: ['CSS', 'HTML', 'VISUALCODE'],
        keywords: ['ANGULAR'],
    },
    {
        id: 18,
        name:'Scrumaster',
        organisation:'Centre8',
        description:'linktraining18',
        financer: 'OPCO',
        dateBeg: new Date(2020,1,3),
        dateEnd: new Date(2020,4,30),
        durationHours: 50,
        dateUpload: new Date(2019,6,25),
        prerequisites: ['CODA', 'HTML'],
        keywords: ['PYTHON'],
    },
    {
        id: 19,
        name:'Developpeur',
        organisation:'Centre5',
        description:'linktraining19',
        financer: 'OPCA',
        dateBeg: new Date(2020,3,23),
        dateEnd: new Date(2020,6,23),
        durationHours: 40,
        dateUpload: new Date(2019,6,23),
        prerequisites: ['PHYTON', 'VISUALCODE'],
        keywords: ['JAVA'],
    },
    {
        id: 20,
        name:'Developpeur',
        organisation:'Centre6',
        description:'linktraining20',
        financer: 'DIF',
        dateBeg: new Date(2020,4,21),
        dateEnd: new Date(2020,6,22),
        durationHours: 120,
        dateUpload: new Date(2019,5,23),
        prerequisites: ['CSS', 'HTML', 'ANGULAR'],
        keywords: ['JAVA'],
    }
]